apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-operator-git # Replace with a new name e.g. tekton-operator-git-v0.14.2-1
spec:
  type: git
  params:
  - name: url
    value: https://github.com/tektoncd/operator
  - name: revision
    value: master # REPLACE with the commit you want to release
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-operator-bucket
spec:
  type: storage
  params:
  - name: type
    value: gcs
  - name: location
    value: gs://tekton-releases/operator
  - name: dir
    value: "y"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: operator-controller-image
spec:
  type: image
  params:
  - name: url
    value: cmd/manager  # Registry is provided via parameter, this is a hack see #569
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: post-release-operator
spec:
  type: cloudEvent
  params:
  - name: targetURI
    value: http://post-release-operator-sink  # This has to be changed to a valid URL
