- op: add
  path: "/rules/-"
  value:
    apiGroups:
    - route.openshift.io
    resources:
    - routes
    verbs:
    - get
    - list
- op: add
  path: "/rules/-"
  value:
    apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - '*'
- op: add
  path: "/rules/-"
  value:
    apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - '*'
- op: add
  path: "/rules/-"
  value:
    apiGroups:
    - console.openshift.io
    resources:
    - consoleyamlsamples
    - consoleclidownloads
    - consolequickstarts
    verbs:
    - '*'
- op: add
  path: "/rules/-"
  value:
    apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    - roles
    verbs:
    - '*'
