kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-default-pipelines-view
  namespace: openshift
roleRef:
  kind: ClusterRole
  name: tekton-default-pipelines-view
  apiGroup: rbac.authorization.k8s.io
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
